import os
import subprocess
import threading
import time
from pathlib import Path

import cv2
import numpy as np
from flask import Flask, Response, jsonify, render_template_string, request
from video_server.video_preprocessor import process_videos

app = Flask(__name__)

FRAME_SIZE = (320, 240)
VIDEO_SERVER_PORT = int(os.getenv("VIDEO_SERVER_PORT", "8123"))

settings_lock = threading.Lock()
settings = {
    "rtsp_url": os.getenv("RTSP_URL", "").strip(),
    "jpeg_quality": int(os.getenv("JPEG_QUALITY", "82")),
    "swap_rb": os.getenv("SWAP_RB", "0") == "1",
    "contrast": float(os.getenv("CONTRAST", "1.12")),
    "brightness": int(os.getenv("BRIGHTNESS", "-4")),
    "saturation": float(os.getenv("SATURATION", "1.18")),
    "preset": os.getenv("STREAM_PRESET", "balanced"),
}

capture_state_lock = threading.Lock()
capture_state = {
    "source": "",
    "status": "starting",
    "last_error": "",
    "last_frame_ms": 0,
}

video_data = []
latest_jpeg = None
latest_lock = threading.Lock()
running = False

PLAYER_DIR = (Path(__file__).resolve().parent.parent / "player").resolve()
LOCAL_OVERRIDES_PATH = PLAYER_DIR / "src" / "LocalOverrides.h"

flash_lock = threading.Lock()
flash_state = {
    "running": False,
    "status": "idle",
    "last_error": "",
    "last_exit_code": None,
    "last_started_ms": 0,
    "last_finished_ms": 0,
    "log_lines": [],
    "active_job": {},
}


def _now_ms():
    return int(time.time() * 1000)


def _get_settings():
    with settings_lock:
        return dict(settings)


def _is_rtsp_mode():
    return len(_get_settings()["rtsp_url"]) > 0


def _set_capture_state(status=None, source=None, last_error=None):
    with capture_state_lock:
        if status is not None:
            capture_state["status"] = status
        if source is not None:
            capture_state["source"] = source
        if last_error is not None:
            capture_state["last_error"] = last_error


def _append_flash_log(line):
    with flash_lock:
        flash_state["log_lines"].append(line.rstrip())
        if len(flash_state["log_lines"]) > 500:
            flash_state["log_lines"] = flash_state["log_lines"][-500:]


def _escape_c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _write_local_overrides(ssid, password, host, port):
    content = f"""#pragma once
// Auto-generated by /admin firmware flasher UI.
// Update values via web UI instead of editing manually.

#define WIFI_SSID "{_escape_c_string(ssid)}"
#define WIFI_PASSWORD "{_escape_c_string(password)}"
#define VIDEO_SERVER_HOST "{_escape_c_string(host)}"
#define VIDEO_SERVER_PORT {int(port)}
"""
    LOCAL_OVERRIDES_PATH.write_text(content, encoding="utf-8")


def _run_flash_job(job):
    env_name = "cheap-yellow-display-no-audio" if job["flavor"] == "no_audio" else "cheap-yellow-display"
    cmd = ["python3", "-m", "platformio", "run", "-e", env_name, "-t", "upload"]
    if job.get("upload_port"):
        cmd.extend(["--upload-port", job["upload_port"]])

    with flash_lock:
        flash_state["running"] = True
        flash_state["status"] = "preparing"
        flash_state["last_error"] = ""
        flash_state["last_exit_code"] = None
        flash_state["last_started_ms"] = _now_ms()
        flash_state["last_finished_ms"] = 0
        flash_state["log_lines"] = []
        flash_state["active_job"] = {
            "flavor": job["flavor"],
            "ssid": job["ssid"],
            "server_host": job["server_host"],
            "server_port": job["server_port"],
            "upload_port": job.get("upload_port", ""),
        }
    _append_flash_log(f"Preparing firmware job: {env_name}")
    _append_flash_log(f"Writing overrides to: {LOCAL_OVERRIDES_PATH}")
    try:
        _write_local_overrides(job["ssid"], job["password"], job["server_host"], job["server_port"])
    except Exception as ex:
        with flash_lock:
            flash_state["running"] = False
            flash_state["status"] = "failed"
            flash_state["last_error"] = f"Failed writing overrides: {ex}"
            flash_state["last_exit_code"] = -1
            flash_state["last_finished_ms"] = _now_ms()
        _append_flash_log(f"ERROR: {flash_state['last_error']}")
        return

    with flash_lock:
        flash_state["status"] = "flashing"
    _append_flash_log("Starting: " + " ".join(cmd))

    proc = subprocess.Popen(
        cmd,
        cwd=str(PLAYER_DIR),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        _append_flash_log(line)
    rc = proc.wait()
    with flash_lock:
        flash_state["running"] = False
        flash_state["last_exit_code"] = rc
        flash_state["last_finished_ms"] = _now_ms()
        if rc == 0:
            flash_state["status"] = "success"
            flash_state["last_error"] = ""
        else:
            flash_state["status"] = "failed"
            flash_state["last_error"] = f"PlatformIO exited with code {rc}"
    _append_flash_log(f"Finished with exit code: {rc}")


def _list_serial_ports():
    ports = []
    for pattern in ("cu.usb*", "cu.wch*", "cu.SLAB*", "ttyUSB*"):
        for path in sorted(Path("/dev").glob(pattern)):
            ports.append("/dev/" + path.name)
    return ports


def _encode_black_frame():
    frame = np.zeros((FRAME_SIZE[1], FRAME_SIZE[0], 3), dtype=np.uint8)
    ok, buf = cv2.imencode(".jpg", frame, [int(cv2.IMWRITE_JPEG_QUALITY), 60])
    return buf.tobytes() if ok else b""


def _fit_frame(frame):
    target_w, target_h = FRAME_SIZE
    src_h, src_w = frame.shape[:2]
    if src_w == 0 or src_h == 0:
        return np.zeros((target_h, target_w, 3), dtype=np.uint8)
    scale = max(target_w / src_w, target_h / src_h)
    resized_w = int(src_w * scale)
    resized_h = int(src_h * scale)
    # Keep downscaling smooth while preserving detail on any upscaled input.
    interpolation = cv2.INTER_AREA if scale < 1.0 else cv2.INTER_LINEAR
    resized = cv2.resize(frame, (resized_w, resized_h), interpolation=interpolation)
    x0 = (resized_w - target_w) // 2
    y0 = (resized_h - target_h) // 2
    return resized[y0:y0 + target_h, x0:x0 + target_w]


def _enhance_frame(frame, contrast, brightness, saturation, preset):
    # Mild contrast/brightness correction plus saturation lift for CYD TFT.
    frame = cv2.convertScaleAbs(frame, alpha=contrast, beta=brightness)
    if saturation != 1.0:
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV).astype(np.float32)
        hsv[:, :, 1] *= saturation
        hsv[:, :, 1] = np.clip(hsv[:, :, 1], 0, 255)
        frame = cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2BGR)
    if preset == "best_quality":
        # Gentle denoise + unsharp mask to recover detail on low-cost TFT.
        frame = cv2.bilateralFilter(frame, d=5, sigmaColor=22, sigmaSpace=22)
        blurred = cv2.GaussianBlur(frame, (0, 0), 1.2)
        frame = cv2.addWeighted(frame, 1.2, blurred, -0.2, 0)
        # Slight gamma lift for punchier midtones.
        gamma = 1.08
        lut = np.array([pow(i / 255.0, 1.0 / gamma) * 255 for i in range(256)]).astype("uint8")
        frame = cv2.LUT(frame, lut)
    return frame


def _rtsp_capture_loop():
    global latest_jpeg
    while running:
        cfg = _get_settings()
        rtsp_url = cfg["rtsp_url"].strip()
        if not rtsp_url:
            _set_capture_state(status="idle", source="", last_error="")
            with latest_lock:
                latest_jpeg = _encode_black_frame()
            time.sleep(0.3)
            continue
        _set_capture_state(status="connecting", source=rtsp_url, last_error="")
        cap = cv2.VideoCapture(rtsp_url)
        if not cap.isOpened():
            _set_capture_state(status="error", source=rtsp_url, last_error="failed to open RTSP stream")
            time.sleep(1.0)
            continue
        _set_capture_state(status="streaming", source=rtsp_url, last_error="")
        last_emit = 0.0
        while running:
            cfg = _get_settings()
            if cfg["rtsp_url"].strip() != rtsp_url:
                # URL changed in UI/API; reconnect with the new stream.
                break
            ok, frame = cap.read()
            if not ok:
                _set_capture_state(status="reconnecting", source=rtsp_url, last_error="stream read failed")
                break
            frame = _fit_frame(frame)
            preset = cfg.get("preset", "balanced")
            frame = _enhance_frame(frame, cfg["contrast"], cfg["brightness"], cfg["saturation"], preset)
            if cfg["swap_rb"]:
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            ok, buf = cv2.imencode(".jpg", frame, [int(cv2.IMWRITE_JPEG_QUALITY), cfg["jpeg_quality"]])
            if ok:
                # Simple output FPS limiter for quality mode, gives CPU headroom to process better.
                now = time.time()
                target_fps = 12 if preset == "best_quality" else 0
                if target_fps > 0 and last_emit > 0 and (now - last_emit) < (1.0 / target_fps):
                    continue
                with latest_lock:
                    latest_jpeg = buf.tobytes()
                last_emit = now
                with capture_state_lock:
                    capture_state["last_frame_ms"] = _now_ms()
                    capture_state["status"] = "streaming"
        cap.release()
        time.sleep(0.5)


def init_video_source():
    global video_data, latest_jpeg, running
    if _is_rtsp_mode():
        latest_jpeg = _encode_black_frame()
        running = True
        threading.Thread(target=_rtsp_capture_loop, daemon=True).start()
        print("RTSP mode enabled")
    else:
        video_data = process_videos("movies", FRAME_SIZE)
        print(f"Movie mode: loaded {len(video_data)} channels from movies/")


def _ensure_movies_loaded():
    global video_data
    if len(video_data) == 0:
        video_data = process_videos("movies", FRAME_SIZE)


@app.route('/channel_info')
def get_channel_lengths():
    if _is_rtsp_mode():
        return jsonify([2_147_483_647])
    _ensure_movies_loaded()
    lengths = [len(audio) for audio, frames in video_data]
    return jsonify(lengths)


@app.route('/audio/<int:channel_index>/<int:start>/<int:length>')
def get_audio(channel_index, start, length):
    if _is_rtsp_mode():
        if length <= 0:
            return Response(b'', mimetype='audio/x-raw')
        return Response(bytes([128]) * length, mimetype='audio/x-raw')
    _ensure_movies_loaded()
    audio, frames = video_data[channel_index % len(video_data)]
    end = start + length
    if end > len(audio):
        end = len(audio)
    if start > end:
        start = end
    if start == end:
        # return nothing - we've got no more data to give
        return Response(b'', mimetype='audio/x-raw')
    slice = audio[start:end]
    return Response(slice, mimetype='audio/x-raw')


@app.route('/frame/<int:channel_index>/<int:ms>')
def get_frame(channel_index, ms):
    if _is_rtsp_mode():
        with latest_lock:
            data = latest_jpeg if latest_jpeg is not None else _encode_black_frame()
        return Response(data, mimetype='image/jpeg')
    _ensure_movies_loaded()
    audio, frames = video_data[channel_index % len(video_data)]
    # use binary search to find the closest frame
    start = 0
    end = len(frames) - 1
    while start <= end:
        mid = (start + end) // 2
        if frames[mid][0] == ms:
            return Response(frames[mid][1], mimetype='image/jpeg')
        elif frames[mid][0] < ms:
            start = mid + 1
        else:
            end = mid - 1
    # we may not find the exact frame, so return the closest frame
    if end < 0:
        end = 0
    elif start >= len(frames):
        start = len(frames) - 1
    return Response(frames[start][1], mimetype='image/jpeg')


@app.route("/preview.mjpg")
def preview_mjpg():
    def _generate():
        boundary = b"--frame\r\n"
        while True:
            with latest_lock:
                frame = latest_jpeg if latest_jpeg is not None else _encode_black_frame()
            yield boundary
            yield b"Content-Type: image/jpeg\r\n\r\n" + frame + b"\r\n"
            time.sleep(0.08)

    return Response(_generate(), mimetype="multipart/x-mixed-replace; boundary=frame")


@app.route("/api/settings", methods=["GET"])
def api_get_settings():
    cfg = _get_settings()
    with capture_state_lock:
        state = dict(capture_state)
    return jsonify({"settings": cfg, "state": state})


@app.route("/api/settings", methods=["POST"])
def api_set_settings():
    payload = request.get_json(silent=True) or {}
    errors = []
    updates = {}

    if "rtsp_url" in payload:
        updates["rtsp_url"] = str(payload["rtsp_url"]).strip()
    if "jpeg_quality" in payload:
        try:
            jpeg_quality = int(payload["jpeg_quality"])
            if jpeg_quality < 40 or jpeg_quality > 95:
                raise ValueError
            updates["jpeg_quality"] = jpeg_quality
        except Exception:
            errors.append("jpeg_quality must be an integer between 40 and 95")
    if "swap_rb" in payload:
        updates["swap_rb"] = bool(payload["swap_rb"])
    if "contrast" in payload:
        try:
            contrast = float(payload["contrast"])
            if contrast < 0.6 or contrast > 1.8:
                raise ValueError
            updates["contrast"] = contrast
        except Exception:
            errors.append("contrast must be between 0.6 and 1.8")
    if "brightness" in payload:
        try:
            brightness = int(payload["brightness"])
            if brightness < -40 or brightness > 40:
                raise ValueError
            updates["brightness"] = brightness
        except Exception:
            errors.append("brightness must be between -40 and 40")
    if "saturation" in payload:
        try:
            saturation = float(payload["saturation"])
            if saturation < 0.6 or saturation > 1.8:
                raise ValueError
            updates["saturation"] = saturation
        except Exception:
            errors.append("saturation must be between 0.6 and 1.8")
    if "preset" in payload:
        preset = str(payload["preset"]).strip()
        if preset not in ("max_fps", "balanced", "best_quality"):
            errors.append("preset must be max_fps, balanced, or best_quality")
        else:
            updates["preset"] = preset

    if errors:
        return jsonify({"ok": False, "errors": errors}), 400

    with settings_lock:
        settings.update(updates)
        applied = dict(settings)
    return jsonify({"ok": True, "settings": applied})


@app.route("/api/flash/status", methods=["GET"])
def api_flash_status():
    with flash_lock:
        data = dict(flash_state)
        data["active_job"] = dict(flash_state["active_job"])
        data["log_lines"] = list(flash_state["log_lines"])
    data["ports"] = _list_serial_ports()
    return jsonify(data)


@app.route("/api/flash", methods=["POST"])
def api_flash_start():
    payload = request.get_json(silent=True) or {}
    flavor = str(payload.get("flavor", "audio_on")).strip()
    ssid = str(payload.get("ssid", "")).strip()
    password = str(payload.get("password", ""))
    server_host = str(payload.get("server_host", "")).strip()
    upload_port = str(payload.get("upload_port", "")).strip()
    try:
        server_port = int(payload.get("server_port", 8124))
    except Exception:
        return jsonify({"ok": False, "error": "server_port must be an integer"}), 400

    if flavor not in ("audio_on", "no_audio"):
        return jsonify({"ok": False, "error": "flavor must be audio_on or no_audio"}), 400
    if not ssid:
        return jsonify({"ok": False, "error": "SSID is required"}), 400
    if not server_host:
        return jsonify({"ok": False, "error": "Server host is required"}), 400
    if server_port < 1 or server_port > 65535:
        return jsonify({"ok": False, "error": "Server port must be 1-65535"}), 400

    with flash_lock:
        if flash_state["running"]:
            return jsonify({"ok": False, "error": "A flash job is already running"}), 409

    job = {
        "flavor": flavor,
        "ssid": ssid,
        "password": password,
        "server_host": server_host,
        "server_port": server_port,
        "upload_port": upload_port,
    }
    threading.Thread(target=_run_flash_job, args=(job,), daemon=True).start()
    return jsonify({"ok": True, "message": "Flash job started"})


@app.route("/admin")
def admin_ui():
    return render_template_string(
        """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>CYD Stream Control</title>
  <style>
    :root {
      --bg-1: #0b1320;
      --bg-2: #16243a;
      --panel: rgba(255,255,255,0.88);
      --ink: #132033;
      --muted: #516176;
      --accent: #0d8fdf;
      --ok: #15803d;
      --warn: #b45309;
      --error: #b91c1c;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: "Space Grotesk", "Avenir Next", "Segoe UI", sans-serif;
      color: var(--ink);
      background:
        radial-gradient(1000px 600px at 90% -10%, #265685, transparent 70%),
        radial-gradient(1000px 700px at -10% 110%, #1c3a59, transparent 70%),
        linear-gradient(160deg, var(--bg-1), var(--bg-2));
      min-height: 100vh;
      padding: 22px;
    }
    .wrap {
      max-width: 1100px;
      margin: 0 auto;
      display: grid;
      grid-template-columns: 1.1fr 1fr;
      gap: 18px;
    }
    .card {
      background: var(--panel);
      border-radius: 16px;
      padding: 18px;
      box-shadow: 0 18px 40px rgba(0,0,0,0.25);
      backdrop-filter: blur(6px);
    }
    h1 {
      margin: 0 0 6px;
      font-size: 26px;
      letter-spacing: .2px;
    }
    p { margin: 0 0 14px; color: var(--muted); }
    .row { margin: 10px 0; }
    label { display:block; font-weight: 700; margin-bottom: 6px; font-size: 14px; }
    input[type="text"], input[type="number"], input[type="range"], select {
      width: 100%;
    }
    input[type="text"], input[type="number"], select {
      border: 1px solid #d6deea;
      border-radius: 10px;
      padding: 10px 12px;
      font-size: 14px;
      background: #fff;
    }
    .inline {
      display: grid;
      grid-template-columns: 1fr 90px;
      gap: 8px;
      align-items: center;
    }
    input[type="range"] { accent-color: var(--accent); }
    .toggle { display: flex; align-items: center; gap: 10px; font-weight: 700; }
    .actions {
      display: flex;
      gap: 8px;
      margin-top: 14px;
    }
    button {
      border: 0;
      border-radius: 10px;
      padding: 10px 14px;
      font-weight: 700;
      cursor: pointer;
    }
    .primary { background: var(--accent); color: #fff; }
    .secondary { background: #e2e8f0; color: #1f2937; }
    .status {
      margin-top: 10px;
      padding: 10px;
      border-radius: 10px;
      background: #eef6ff;
      font-size: 13px;
    }
    .status.ok { color: var(--ok); }
    .status.warn { color: var(--warn); }
    .status.err { color: var(--error); }
    .preview {
      width: 100%;
      aspect-ratio: 4 / 3;
      object-fit: cover;
      border-radius: 12px;
      border: 2px solid #d7e2ef;
      background: #0c1420;
    }
    .meta {
      margin-top: 8px;
      color: #445468;
      font-size: 13px;
      display: grid;
      gap: 3px;
    }
    @media (max-width: 900px) {
      .wrap { grid-template-columns: 1fr; }
    }
    .span-2 { grid-column: 1 / -1; }
    .mono {
      font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
      background: #0d1726;
      color: #d5e3f4;
      border-radius: 10px;
      padding: 10px;
      min-height: 220px;
      max-height: 320px;
      overflow: auto;
      white-space: pre-wrap;
      font-size: 12px;
      border: 1px solid #263a56;
    }
    .pill {
      display: inline-block;
      font-weight: 700;
      font-size: 12px;
      border-radius: 999px;
      padding: 4px 10px;
      background: #dbeafe;
      color: #1e3a8a;
      margin-bottom: 8px;
    }
    .firm-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 10px;
    }
    @media (max-width: 900px) {
      .firm-grid { grid-template-columns: 1fr; }
    }
  </style>
</head>
<body>
  <div class="wrap">
    <section class="card">
      <h1>CYD Stream Control</h1>
      <p>Update URL and image tuning live. Changes are applied immediately.</p>

      <div class="row">
        <label for="rtsp_url">RTSP URL</label>
        <input id="rtsp_url" type="text" placeholder="rtsp://user:pass@ip:port/path" />
      </div>

      <div class="row">
        <label for="jpeg_quality">JPEG Quality</label>
        <div class="inline">
          <input id="jpeg_quality" type="range" min="40" max="95" step="1" />
          <input id="jpeg_quality_num" type="number" min="40" max="95" step="1" />
        </div>
      </div>

      <div class="row">
        <label for="contrast">Contrast</label>
        <div class="inline">
          <input id="contrast" type="range" min="0.6" max="1.8" step="0.01" />
          <input id="contrast_num" type="number" min="0.6" max="1.8" step="0.01" />
        </div>
      </div>

      <div class="row">
        <label for="brightness">Brightness</label>
        <div class="inline">
          <input id="brightness" type="range" min="-40" max="40" step="1" />
          <input id="brightness_num" type="number" min="-40" max="40" step="1" />
        </div>
      </div>

      <div class="row">
        <label for="saturation">Saturation</label>
        <div class="inline">
          <input id="saturation" type="range" min="0.6" max="1.8" step="0.01" />
          <input id="saturation_num" type="number" min="0.6" max="1.8" step="0.01" />
        </div>
      </div>

      <div class="row toggle">
        <input id="swap_rb" type="checkbox" />
        <label for="swap_rb" style="margin:0">Swap Red/Blue Channels</label>
      </div>

      <div class="actions">
        <button class="primary" id="save_btn">Apply Settings</button>
        <button class="secondary" id="refresh_btn">Reload Current</button>
        <button class="secondary" id="preset_fps_btn">Preset: Max FPS</button>
        <button class="secondary" id="preset_quality_btn">Preset: Best Quality</button>
      </div>
      <div id="status_box" class="status">Loading…</div>
    </section>

    <section class="card">
      <img class="preview" src="/preview.mjpg" alt="Live Preview" />
      <div class="meta">
        <div><strong>Status:</strong> <span id="meta_status">-</span></div>
        <div><strong>Source:</strong> <span id="meta_source">-</span></div>
        <div><strong>Last frame:</strong> <span id="meta_frame">-</span></div>
        <div><strong>Last error:</strong> <span id="meta_error">-</span></div>
      </div>
    </section>

    <section class="card span-2">
      <div class="pill">Firmware Flasher</div>
      <p>Build and flash CYD firmware directly from this server.</p>
      <div class="firm-grid">
        <div class="row">
          <label for="fw_flavor">Firmware Flavor</label>
          <select id="fw_flavor">
            <option value="audio_on">Audio On</option>
            <option value="no_audio">Audio Off (Higher FPS)</option>
          </select>
        </div>
        <div class="row">
          <label for="fw_upload_port">USB Port (optional)</label>
          <input id="fw_upload_port" type="text" placeholder="/dev/cu.usbserial-1110" />
        </div>
        <div class="row">
          <label for="fw_ssid">Wi-Fi SSID</label>
          <input id="fw_ssid" type="text" placeholder="Your Wi-Fi name" />
        </div>
        <div class="row">
          <label for="fw_password">Wi-Fi Password</label>
          <input id="fw_password" type="text" placeholder="Your Wi-Fi password" />
        </div>
        <div class="row">
          <label for="fw_server_host">Server Host/IP</label>
          <input id="fw_server_host" type="text" placeholder="192.168.1.72" />
        </div>
        <div class="row">
          <label for="fw_server_port">Server Port</label>
          <input id="fw_server_port" type="number" min="1" max="65535" step="1" value="8124" />
        </div>
      </div>
      <div class="actions">
        <button class="primary" id="flash_btn">Build + Flash CYD</button>
        <button class="secondary" id="refresh_flash_btn">Refresh Flash Status</button>
      </div>
      <div id="flash_status_box" class="status">Idle</div>
      <div id="flash_ports" class="meta"></div>
      <div id="flash_log" class="mono"></div>
    </section>
  </div>

  <script>
    const ids = ["jpeg_quality", "contrast", "brightness", "saturation"];
    function bindPair(id) {
      const slider = document.getElementById(id);
      const number = document.getElementById(id + "_num");
      slider.addEventListener("input", () => number.value = slider.value);
      number.addEventListener("input", () => slider.value = number.value);
    }
    ids.forEach(bindPair);

    const statusBox = document.getElementById("status_box");
    function setStatus(msg, mode) {
      statusBox.textContent = msg;
      statusBox.className = "status " + (mode || "");
    }

    const flashStatusBox = document.getElementById("flash_status_box");
    const flashLog = document.getElementById("flash_log");
    const flashPorts = document.getElementById("flash_ports");
    function setFlashStatus(msg, mode) {
      flashStatusBox.textContent = msg;
      flashStatusBox.className = "status " + (mode || "");
    }

    let isDirty = false;

    function applySettingsToForm(s) {
      document.getElementById("rtsp_url").value = s.rtsp_url || "";
      document.getElementById("jpeg_quality").value = s.jpeg_quality;
      document.getElementById("jpeg_quality_num").value = s.jpeg_quality;
      document.getElementById("contrast").value = s.contrast;
      document.getElementById("contrast_num").value = s.contrast;
      document.getElementById("brightness").value = s.brightness;
      document.getElementById("brightness_num").value = s.brightness;
      document.getElementById("saturation").value = s.saturation;
      document.getElementById("saturation_num").value = s.saturation;
      document.getElementById("swap_rb").checked = !!s.swap_rb;
    }

    function updateState(st) {
      st = st || {};
      document.getElementById("meta_status").textContent = st.status || "-";
      document.getElementById("meta_source").textContent = st.source || "-";
      document.getElementById("meta_error").textContent = st.last_error || "-";
      if (st.last_frame_ms) {
        document.getElementById("meta_frame").textContent = new Date(st.last_frame_ms).toLocaleTimeString();
      } else {
        document.getElementById("meta_frame").textContent = "-";
      }
    }

    function hydrate(data) {
      const s = data.settings;
      if (!isDirty && s) {
        applySettingsToForm(s);
      }
      updateState(data.state || {});
    }

    async function loadSettings() {
      const res = await fetch("/api/settings");
      const data = await res.json();
      isDirty = false;
      hydrate(data);
      setStatus("Settings loaded", "ok");
    }

    async function saveSettings() {
      const payload = {
        rtsp_url: document.getElementById("rtsp_url").value.trim(),
        jpeg_quality: Number(document.getElementById("jpeg_quality_num").value),
        contrast: Number(document.getElementById("contrast_num").value),
        brightness: Number(document.getElementById("brightness_num").value),
        saturation: Number(document.getElementById("saturation_num").value),
        swap_rb: document.getElementById("swap_rb").checked
      };
      const res = await fetch("/api/settings", {
        method: "POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      if (!res.ok) {
        setStatus((data.errors || ["Failed to apply settings"]).join(" | "), "err");
        return;
      }
      isDirty = false;
      hydrate({settings: data.settings, state: {}});
      setStatus("Applied. Stream will reconnect if URL changed.", "ok");
    }

    async function applyPreset(kind) {
      const presets = {
        max_fps: { preset: "max_fps", jpeg_quality: 68, contrast: 1.06, brightness: -2, saturation: 1.08 },
        best_quality: { preset: "best_quality", jpeg_quality: 88, contrast: 1.18, brightness: -6, saturation: 1.24 }
      };
      const p = presets[kind];
      if (!p) return;
      const res = await fetch("/api/settings", {
        method: "POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify(p)
      });
      const data = await res.json();
      if (!res.ok) {
        setStatus((data.errors || ["Failed to apply preset"]).join(" | "), "err");
        return;
      }
      isDirty = false;
      hydrate({settings: data.settings, state: {}});
      setStatus(`Preset applied: ${kind}`, "ok");
    }

    document.getElementById("save_btn").addEventListener("click", saveSettings);
    document.getElementById("refresh_btn").addEventListener("click", loadSettings);
    document.getElementById("preset_fps_btn").addEventListener("click", () => applyPreset("max_fps"));
    document.getElementById("preset_quality_btn").addEventListener("click", () => applyPreset("best_quality"));
    document.querySelectorAll("input").forEach((el) => {
      el.addEventListener("input", () => { isDirty = true; });
      el.addEventListener("change", () => { isDirty = true; });
    });

    function populateFirmwareDefaultsFromSettings() {
      const url = document.getElementById("rtsp_url").value || "";
      const m = url.match(/@([^:/]+)(?::\\d+)?\\//);
      document.getElementById("fw_server_host").value = (m && m[1]) ? m[1] : "192.168.1.72";
      document.getElementById("fw_server_port").value = 8124;
    }

    async function loadFlashStatus() {
      const res = await fetch("/api/flash/status");
      const data = await res.json();
      const status = data.status || "idle";
      const running = !!data.running;
      const label = running ? `Running: ${status}` : `Last: ${status}`;
      setFlashStatus(label + (data.last_error ? ` | ${data.last_error}` : ""), running ? "warn" : (status === "success" ? "ok" : (status === "failed" ? "err" : "")));
      flashLog.textContent = (data.log_lines || []).join("\\n");
      flashLog.scrollTop = flashLog.scrollHeight;
      const ports = data.ports || [];
      flashPorts.innerHTML = `<div><strong>Detected USB Ports:</strong> ${ports.length ? ports.join(", ") : "none detected"}</div>`;
      if (!document.getElementById("fw_upload_port").value && ports.length === 1) {
        document.getElementById("fw_upload_port").value = ports[0];
      }
    }

    async function startFlash() {
      const payload = {
        flavor: document.getElementById("fw_flavor").value,
        ssid: document.getElementById("fw_ssid").value.trim(),
        password: document.getElementById("fw_password").value,
        server_host: document.getElementById("fw_server_host").value.trim(),
        server_port: Number(document.getElementById("fw_server_port").value),
        upload_port: document.getElementById("fw_upload_port").value.trim()
      };
      const res = await fetch("/api/flash", {
        method: "POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      if (!res.ok) {
        setFlashStatus(data.error || "Failed to start flash job", "err");
        return;
      }
      setFlashStatus("Flash started", "warn");
      await loadFlashStatus();
    }

    document.getElementById("flash_btn").addEventListener("click", startFlash);
    document.getElementById("refresh_flash_btn").addEventListener("click", loadFlashStatus);

    loadSettings().catch(() => setStatus("Failed to load settings", "err"));
    populateFirmwareDefaultsFromSettings();
    loadFlashStatus().catch(() => setFlashStatus("Failed to load flash status", "err"));
    setInterval(() => {
      fetch("/api/settings")
        .then(r => r.json())
        .then(d => updateState(d.state))
        .catch(() => {});
    }, 1500);
    setInterval(() => {
      loadFlashStatus().catch(() => {});
    }, 2000);
  </script>
</body>
</html>"""
    )


if __name__ == '__main__':
    init_video_source()
    app.run(host='0.0.0.0', port=VIDEO_SERVER_PORT)
